server:
  port: 8081

#person:
#  name: Horatio
#  hometown: shaoxing
#  birthday: 1992/5/14
#
#
#  maps: {k1: shanghai, k2: hangzhou}
#  hobbies:
#    - swim
#    - bike
#
#  dog:
#    name: spike
#    age: 5

